# Generated by Django 5.2.11 on 2026-02-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean')], default='float', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('exchange_mic', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('cash_flow_per_share_annual', models.FloatField(blank=True, null=True)),
                ('long_term_debt_to_equity_annual', models.FloatField(blank=True, null=True)),
                ('ten_day_avg_trading_volume', models.FloatField(blank=True, null=True)),
                ('fundamentals_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='OptionsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('dte_at_snapshot', models.IntegerField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('implied_volatility', models.FloatField(blank=True, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('spread_pct', models.FloatField(blank=True, null=True)),
                ('open_interest', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_snapshots', to='screener.symbol')),
            ],
            options={
                'ordering': ['symbol', 'expiry_date', 'strike'],
                'indexes': [models.Index(fields=['symbol', 'snapshot_date'], name='screener_op_symbol__5c4856_idx'), models.Index(fields=['expiry_date'], name='screener_op_expiry__bec072_idx')],
            },
        ),
        migrations.CreateModel(
            name='IVRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_date', models.DateField()),
                ('iv_rank', models.FloatField(help_text='0-100 scale')),
                ('iv_percentile', models.FloatField(blank=True, null=True)),
                ('weeks_of_history', models.IntegerField(default=0)),
                ('is_reliable', models.BooleanField(default=False, help_text='True when >= 52 weeks of history')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv_ranks', to='screener.symbol')),
            ],
            options={
                'ordering': ['-computed_date'],
                'unique_together': {('symbol', 'computed_date')},
            },
        ),
        migrations.CreateModel(
            name='EarningsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('source', models.CharField(default='finnhub', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_dates', to='screener.symbol')),
            ],
            options={
                'ordering': ['report_date'],
                'unique_together': {('symbol', 'report_date')},
            },
        ),
    ]
