# Generated by Django 5.2.11 on 2026-02-23 22:17

from django.db import migrations


def seed_filter_config(apps, schema_editor):
    FilterConfig = apps.get_model("screener", "FilterConfig")
    defaults = [
        ("market_cap_min", "10000000000", "int", "Minimum market cap in USD"),
        ("operating_margin_min", "0.0", "float", "Minimum operating margin (0.0 = breakeven or better)"),
        ("free_cash_flow_min", "0", "float", "Minimum cash flow per share (annual)"),
        ("avg_daily_dollar_volume_min", "100000000", "int", "Minimum 10-day avg dollar volume ($100M)"),
        ("debt_to_equity_max", "2.0", "float", "Maximum long-term debt/equity ratio"),
        ("earnings_exclusion_days", "50", "int", "Exclude tickers with earnings within N calendar days"),
        ("iv_rank_min", "70", "float", "Minimum IV rank (0-100) — below this is not elevated enough"),
        ("iv_rank_max", "90", "float", "Maximum IV rank (0-100) — above this may signal distress"),
        ("iv_min", "0.20", "float", "Minimum implied volatility (20%)"),
        ("iv_max", "0.40", "float", "Maximum implied volatility (40%)"),
        ("delta_target_min", "0.15", "float", "Minimum abs(delta) for candidate puts"),
        ("delta_target_max", "0.30", "float", "Maximum abs(delta) for candidate puts"),
        ("otm_pct_target", "0.175", "float", "Target OTM percentage (17.5%)"),
        ("expiry_dte_min", "30", "int", "Minimum days to expiry for target contracts"),
        ("expiry_dte_max", "45", "int", "Maximum days to expiry for target contracts"),
        ("risk_free_rate", "0.043", "float", "3-month T-bill rate used in Black-Scholes delta calculation"),
    ]
    for key, value, value_type, description in defaults:
        FilterConfig.objects.get_or_create(
            key=key,
            defaults={"value": value, "value_type": value_type, "description": description},
        )


def reverse_seed(apps, schema_editor):
    FilterConfig = apps.get_model("screener", "FilterConfig")
    keys = [
        "market_cap_min", "operating_margin_min", "free_cash_flow_min",
        "avg_daily_dollar_volume_min", "debt_to_equity_max",
        "earnings_exclusion_days", "iv_rank_min", "iv_rank_max",
        "iv_min", "iv_max", "delta_target_min", "delta_target_max",
        "otm_pct_target", "expiry_dte_min", "expiry_dte_max", "risk_free_rate",
    ]
    FilterConfig.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_filter_config, reverse_code=reverse_seed),
    ]
