# Generated by Django 5.2.11 on 2026-02-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_seed_otm_pct_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='IV30Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('iv30', models.FloatField(help_text='30-day implied volatility (decimal, e.g. 0.28)')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv30_snapshots', to='screener.symbol')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
