# Generated by Django 5.2.11 on 2026-02-28 00:32

from django.db import migrations, models


def deduplicate_options_snapshots(apps, schema_editor):
    """Remove duplicate OptionsSnapshot rows, keeping the one with the lowest pk."""
    db = schema_editor.connection
    with db.cursor() as cursor:
        cursor.execute("""
            DELETE FROM screener_optionssnapshot
            WHERE id NOT IN (
                SELECT MIN(id)
                FROM screener_optionssnapshot
                GROUP BY symbol_id, snapshot_date, expiry_date, strike
            )
        """)
        if cursor.rowcount:
            print(f"  Removed {cursor.rowcount} duplicate OptionsSnapshot rows")


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_remove_avg_daily_dollar_volume'),
    ]

    operations = [
        migrations.RunPython(deduplicate_options_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='optionssnapshot',
            constraint=models.UniqueConstraint(fields=('symbol', 'snapshot_date', 'expiry_date', 'strike'), name='unique_option_snapshot'),
        ),
    ]
