# Generated by Django 5.2.11 on 2026-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_unique_option_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ivrank',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='ivrank',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ivrank',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_ivrank_per_symbol'),
        ),
    ]
