# Generated by Django 5.2.11 on 2026-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_alter_ivrank_options_alter_ivrank_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='suppress_until',
            field=models.DateField(blank=True, help_text='Hide from candidates until this date (exclusive — reappears day after)', null=True),
        ),
    ]
