# Generated by Django 5.2.11 on 2026-03-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0010_symbol_suppress_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionsSnapshot',
        ),
    ]
