# Generated by Django 5.2.11 on 2026-03-10 15:07

from django.db import migrations, models
from django.db.models import F


def convert_volume_and_update_configs(apps, schema_editor):
    """Convert volume from millions to raw shares, update FilterConfig units."""
    Symbol = apps.get_model("screener", "Symbol")
    FilterConfig = apps.get_model("screener", "FilterConfig")

    # Convert existing volume data from millions to raw shares
    Symbol.objects.filter(avg_volume_10d__isnull=False).update(
        avg_volume_10d=F("avg_volume_10d") * 1_000_000
    )

    # Update min_avg_volume threshold: 1.5 (millions) -> 1500000 (raw shares)
    FilterConfig.objects.filter(key="min_avg_volume").update(
        value="1500000",
        description="Minimum 10-day average trading volume (shares)",
    )

    # Update debt_to_equity_max: 2.0 (ratio) -> 200.0 (percentage, Yahoo scale)
    FilterConfig.objects.filter(key="debt_to_equity_max").update(
        value="200.0",
        description="Maximum total debt/equity (Yahoo percentage scale, 200 = 2x)",
    )

    # Update free_cash_flow_min description
    FilterConfig.objects.filter(key="free_cash_flow_min").update(
        description="Minimum free cash flow (absolute USD, 0 = positive FCF)",
    )


def reverse_convert(apps, schema_editor):
    Symbol = apps.get_model("screener", "Symbol")
    FilterConfig = apps.get_model("screener", "FilterConfig")

    Symbol.objects.filter(avg_volume_10d__isnull=False).update(
        avg_volume_10d=F("avg_volume_10d") / 1_000_000
    )
    FilterConfig.objects.filter(key="min_avg_volume").update(
        value="1.5",
        description="Minimum 10-day average trading volume (millions of shares)",
    )
    FilterConfig.objects.filter(key="debt_to_equity_max").update(
        value="2.0",
        description="Maximum long-term debt/equity ratio",
    )
    FilterConfig.objects.filter(key="free_cash_flow_min").update(
        description="Minimum cash flow per share (annual)",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0011_delete_optionssnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='cash_flow_per_share_annual',
            new_name='free_cash_flow',
        ),
        migrations.RenameField(
            model_name='symbol',
            old_name='long_term_debt_to_equity_annual',
            new_name='debt_to_equity',
        ),
        migrations.RenameField(
            model_name='symbol',
            old_name='ten_day_avg_trading_volume',
            new_name='avg_volume_10d',
        ),
        migrations.RunPython(convert_volume_and_update_configs, reverse_code=reverse_convert),
    ]
