# Generated by Django 5.2.11 on 2026-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0012_rename_fundamental_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv30snapshot',
            name='iv30_yfinance',
            field=models.FloatField(default=0.0, help_text='30-day implied volatility from yfinance (decimal, e.g. 0.28)'),
        ),
        migrations.AlterField(
            model_name='iv30snapshot',
            name='iv30',
            field=models.FloatField(blank=True, help_text='30-day implied volatility from DoltHub (decimal, e.g. 0.28)', null=True),
        ),
    ]
