# Generated by Django 5.2.11 on 2026-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0013_iv30snapshot_iv30_yfinance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv30snapshot',
            name='iv30_yfinance',
            field=models.FloatField(blank=True, help_text='30-day implied volatility from yfinance (decimal, e.g. 0.28)', null=True),
        ),
    ]
