# Generated by Django 5.2.11 on 2026-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0015_drop_iv30_rename_yfinance'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='has_options',
            field=models.BooleanField(default=True, help_text='False if yfinance reports no options chain — skipped in IV pulls'),
        ),
    ]
